# Generated by Django 6.0.6 on 2026-08-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
